apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: k8s-demo2
    image: docker pull nginx
    ports:
    - name: nginx-port
      containerPort: 80
  
